# Candace Savonen Apr 2021

name: Delete Preview

on:
  pull_request:
    types: [closed]

jobs:
  delete-preview:
    runs-on: ubuntu-latest
    steps:

      # This is because if a PR is closed before a render finishes it won't find it.
      - name: Sleep for 5 minutes
        run: sleep 300s
        shell: bash

      # Delete the branch!
      - name: Delete branch locally and remotely
        run: |
        git branch -d preview-${{ github.event.pull_request.number }}
        git push origin --delete preview-${{ github.event.pull_request.number }}
