# This code was adapted from code written by Josh Shapiro
# for the Childhood Cancer Data Lab, an initiative of Alexs Lemonade Stand Foundation.
# https://github.com/AlexsLemonade/exercise-notebook-answers

# Adapted for this jhudsl repository by Candace Savonen Apr 2021

name: Copy files from Bookdown to Leanpub repo
# Copy rendered notebooks to Leanpub repo

# This workflow will run when there are changes to docs/ files in THIS repo
on:
  workflow_dispatch:
  # Only run after the render finishes running
  workflow_run:
    workflows: [ "Build, Render, and Push" ]
    branches: [ main ]
    types:
      - completed

jobs:
  file-bookdown-pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Get repository name by dropping Bookdown if it exists but always append _Leanpub
    steps:
      - name: Get repository name
        id: get_repo_name
        shell: bash
        run: |
          LEANPUB_REPO=$(echo ${GITHUB_REPOSITORY} | sed "s/_Bookdown/ /g" | awk '{print $1"_Leanpub"}')
          echo $LEANPUB_REPO

      - name: Set up test for if LEANPUB REPO EXISTS
        run: |
          LEANPUB_REPO_EXISTS=$(git ls-remote https://github.com/$LEANPUB_REPO > /dev/null 2>&1)
          FALSE=false
          if [ "$?" -ne 0 ]; then
            LEANPUB_REPO_EXISTS=false
            echo "'$LEANPUB_REPO' does not exist in GitHub; skipping transfer"
          fi

      - name: Quit if LEANPUB_REPO doesn't exist
        if: ${{ steps.spell_check_run.outputs.LEANPUB_REPO_EXISTS == steps.spell_check_run.outputs.FALSE }}
        run:
          set +e
          exit 1
          set -e

      - name: Checkout code from Leanpub repo
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.get_repo_name.outputs.LEANPUB_REPO }}
          token: ${{ secrets.GH_PAT }}

      - name: Get files from Bookdown repo
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          sudo apt-get install subversion
          sudo apt install r-base
          sudo Rscript -e "install.packages('yaml')"

          if [ -d "docs/" ]
          then
            # remove old docs/ files and folder
            rm -r docs/*
          fi
          # Copy over docs folder
          svn export --force https://github.com/${GITHUB_REPOSITORY}.git/branches/${GITHUB_REF#refs/heads/}/docs

          # Copy over book.bib file
          svn export --force https://github.com/${GITHUB_REPOSITORY}.git/branches/${GITHUB_REF#refs/heads/}/book.bib

          # Get assets folder
          svn export --force https://github.com/${GITHUB_REPOSITORY}.git/branches/${GITHUB_REF#refs/heads/}/assets

          # Copy over _bookdown.yml
          svn export --force https://github.com/${GITHUB_REPOSITORY}.git/branches/${GITHUB_REF#refs/heads/}/_bookdown.yml

          # Copy over _output.ymls
          svn export --force https://github.com/${GITHUB_REPOSITORY}.git/branches/${GITHUB_REF#refs/heads/}/_output.yml

          # Copy over images folder
          svn export --force https://github.com/${GITHUB_REPOSITORY}.git/branches/${GITHUB_REF#refs/heads/}/resources/ resources/

          # Get list of Rmds needing to copy
          Rscript --vanilla scripts/get_rmd_filenames.R

          # the url from this repo where files will be downloaded from
          base_url=https://${GH_PAT}@raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_REF#refs/heads/}

          # remove old Rmd files
          rm $(find . -name '*.Rmd'  | grep '.Rmd' )

          input="resources/rmd_list.txt"
          while IFS= read -r line
          do
            echo "$line"
            curl --fail -s ${base_url}/${line} > ${line}
          done < "$input"

      - name: Create PR with rendered docs files
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: Copy files from Bookdown repository
          signoff: false
          branch: auto_copy_rendered_files
          delete-branch: true
          title: 'GHA: Automated transfer of leanbuild-needed files from Bookdown repository'
          body: |
            ### Description:
             Copying over the leanbuild-needed files from Bookdown repository:
               - Rmds listed in the _bookdoown.yml
               - _bookdown.yml
               - docs/*
               - book.bib
               - resources/*
               - _output.yml
          labels: |
            automated
          reviewers: $GITHUB_ACTOR

      # Write out PR info
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
